name: ArduinoBuild(platform-version 2.x)

env:
  SKETCH_NAME: build_test.ino
  SKETCH_NAMES_FIND_START: ./examples/workflow
  REQUIRED_LIBRARIES:

on:
  push:
    paths:
    - '**.ino'
    - '**.cpp'
    - '**.hpp'
    - '**.h'
    - '**.c'
    - '**.inl'
    - '**ArduinoBuild_2.yml'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{matrix.board}}@${{matrix.platform-version}}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      #max-parallel: 1
      matrix:
        platform-url:
          - https://espressif.github.io/arduino-esp32/package_esp32_index.json

        board:
          - m5stack-core-esp32
          - m5stack-core2
          - m5stack-atoms3
          - m5stack-cores3

        platform-version:
          #- 2.0.15
          #- 2.0.16
          - 2.0.17

        platform:
          - esp32

        archi:
          - esp32

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Checkout M5Unified
        uses: actions/checkout@v4
        with:
          repository: m5stack/M5Unified
          #ref: develop
          path: CustomLibrary_M5Unified

      - name: Checkout M5GFX
        uses: actions/checkout@v4
        with:
          repository: m5stack/M5GFX
          #ref: develop
          path: CustomLibrary_M5GFX

      - name: Compile build_test
        uses: ArminJo/arduino-test-compile@master
        with:
          arduino-board-fqbn: ${{ matrix.platform }}:${{ matrix.archi }}:${{ matrix.board }}
          arduino-platform: ${{ matrix.platform }}:${{ matrix.archi }}@${{ matrix.platform-version }}
          platform-url: ${{ matrix.platform-url }}
          required-libraries: ${{ env.REQUIRED_LIBRARIES }}
          extra-arduino-cli-args: ${{ matrix.cli-args }}
          #build-properties: ${{ toJson(matrix.build-properties) }}
          sketch-names: ${{ env.SKETCH_NAME }}
          sketch-names-find-start: ${{ env.SKETCH_NAMES_FIND_START }}
          #sketches-exclude: ${{ matrix.sketches-exclude }}
