name: clang-format Check

env:
  INCLUDE_REGEX: ^.*\.((((c|C)(c|pp|xx|\+\+)?$)|((h|H)h?(pp|xx|\+\+)?$))|(inl|ino|pde|proto|cu))$

on:
  push:
    paths:
      - '**.ino'
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - '**.c'
      - '**.inl'
      - '**clang-format-check.yml'
      - '**.clang-format'
  pull_request:
    paths:
      - '**.ino'
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - '**.c'
      - '**.inl'
      - '**clang-format-check.yml'
      - '**.clang-format'
  workflow_dispatch:

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - check: 'src'
            exclude: '^.*[\/](optional|expected)\.(hpp)$'
          - check: 'test'
            exclude: ''
          - check: 'examples'
            exclude: ''

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.10.2 # Using include-regex 10.x or later
        with:
          clang-format-version: '13'
          check-path: ${{ matrix.path['check'] }}
          exclude-regex: ${{ matrix.path['exclude'] }}
          include-regex: ${{ env.INCLUDE_REGEX }}

