name: Deploy Doxygen docuemnt on GitHub Pages
on:
#  workflow_dispatch:
  on:  [push]
# on: [released]
# branches:
#   - main
#   - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/doxygen@develop
        with:
          doxygen_version: 1.11.0
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/html
          config_file: docs/Doxyfile
