name: Deploy Doxygen docuemnt on GitHub Pages
on:  [push, workflow_dispatch]
# on: [released, workflow_dispatch]
# branches:
#   - main
#   - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: Make document
        uses: ./.github/actions/doxygen
        with:
          doxygen_version: 1.11.0
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/html
          config_file: docs/Doxyfile
