name: Build(platformio)

on:
  push:
    tags-ignore:
      - '*.*.*'
      - 'v*.*.*'
    branches:
      - '*'
    paths:
      - 'src/unit/**.cpp'
      - 'src/unit/**.hpp'
      - 'src/unit/**.h'
      - 'src/unit/**.c'
      - 'test/**.cpp'
      - 'test/**.hpp'
      - 'test/**.h'
      - 'test/**.c'
      - '**/platformio-build-check.yml'
      - '**/platformio.ini'
  pull_request:
    paths:
      - 'src/unit/**.cpp'
      - 'src/unit/**.hpp'
      - 'src/unit/**.h'
      - 'src/unit/**.c'
      - 'test/**.cpp'
      - 'test/**.hpp'
      - 'test/**.h'
      - 'test/**.c'
      - '**/platformio-build-check.yml'
      - '**/platformio.ini'
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  build:
    name: ${{ matrix.board }}:${{ matrix.framework }}:${{ matrix.espressif32 }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      fail-fast: false
      max-parallel: 20
      
      matrix:
        board:
          - Core
          - Core2
          - CoreS3
          - Fire
          - StampS3
          - Dial
          - AtomMatrix
          - AtomS3
          - AtomS3R
          - NanoC6
          - StickCPlus
          - StickCPlus2
          - Paper
          - CoreInk

        framework:
          - Arduino

        espressif32:
          - latest
#          - '5_4_0'
#          - '4_4_0'

#        exclude:
#          - board: CoreS3
#            espressif32: '5_4_0'
#          - board: CoreS3
#            espressif32: '4_4_0'
#          - board: StampS3
#            espressif32: '5_4_0'
#          - board: StampS3
#            espressif32: '4_4_0'
#          - board: AtomS3
#            espressif32: '5_4_0'
#          - board: AtomS3
#            espressif32: '4_4_0'
#          - board: Dial
#            espressif32: '5_4_0'
#          - board: Dial
#            espressif32: '4_4_0'
#          - board: NanoC6
#            espressif32: '5_4_0'
#          - board: NanoC6
#            espressif32: '4_4_0'
#          - board: StickCPlus
#            espressif32: '5_4_0'
#          - board: StickCPlus
#            espressif32: '4_4_0'
#          - board: Paper
#            espressif32: '5_4_0'
#          - board: Paper
#            espressif32: '4_4_0'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build examples
        uses: m5stack/M5Utility/.github/actions/pio_test_build@develop
        with:
          environments: test_${{ matrix.board }}
#         targets:
          project-dir: "./"
          project-conf: "./platformio.ini"
#          jobs: 6
#          silent: false
#          verbose: true
#          disable-auto-clean: false
